# Generated by Django 6.0.1 on 2026-01-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_otp_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_time_stamp',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='otp_verified',
            field=models.BooleanField(default=True),
        ),
    ]
